/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentRecommendationsRouteImport } from './routes/student.recommendations'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentMockInterviewRouteImport } from './routes/student.mock-interview'
import { Route as StudentInterviewPrepRouteImport } from './routes/student.interview-prep'
import { Route as StudentBrowseRouteImport } from './routes/student.browse'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentRecommendationsRoute = StudentRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMockInterviewRoute = StudentMockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => StudentRoute,
} as any)
const StudentInterviewPrepRoute = StudentInterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBrowseRoute = StudentBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/browse': typeof StudentBrowseRoute
  '/student/interview-prep': typeof StudentInterviewPrepRoute
  '/student/mock-interview': typeof StudentMockInterviewRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/browse': typeof StudentBrowseRoute
  '/student/interview-prep': typeof StudentInterviewPrepRoute
  '/student/mock-interview': typeof StudentMockInterviewRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/browse': typeof StudentBrowseRoute
  '/student/interview-prep': typeof StudentInterviewPrepRoute
  '/student/mock-interview': typeof StudentMockInterviewRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/opportunities'
    | '/admin/reports'
    | '/admin/students'
    | '/student/applications'
    | '/student/browse'
    | '/student/interview-prep'
    | '/student/mock-interview'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/recommendations'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/opportunities'
    | '/admin/reports'
    | '/admin/students'
    | '/student/applications'
    | '/student/browse'
    | '/student/interview-prep'
    | '/student/mock-interview'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/recommendations'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/opportunities'
    | '/admin/reports'
    | '/admin/students'
    | '/student/applications'
    | '/student/browse'
    | '/student/interview-prep'
    | '/student/mock-interview'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/recommendations'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/recommendations': {
      id: '/student/recommendations'
      path: '/recommendations'
      fullPath: '/student/recommendations'
      preLoaderRoute: typeof StudentRecommendationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/mock-interview': {
      id: '/student/mock-interview'
      path: '/mock-interview'
      fullPath: '/student/mock-interview'
      preLoaderRoute: typeof StudentMockInterviewRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/interview-prep': {
      id: '/student/interview-prep'
      path: '/interview-prep'
      fullPath: '/student/interview-prep'
      preLoaderRoute: typeof StudentInterviewPrepRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/browse': {
      id: '/student/browse'
      path: '/browse'
      fullPath: '/student/browse'
      preLoaderRoute: typeof StudentBrowseRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentBrowseRoute: typeof StudentBrowseRoute
  StudentInterviewPrepRoute: typeof StudentInterviewPrepRoute
  StudentMockInterviewRoute: typeof StudentMockInterviewRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
  StudentRecommendationsRoute: typeof StudentRecommendationsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentBrowseRoute: StudentBrowseRoute,
  StudentInterviewPrepRoute: StudentInterviewPrepRoute,
  StudentMockInterviewRoute: StudentMockInterviewRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
  StudentRecommendationsRoute: StudentRecommendationsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
